version: "3.1"

services:
    mysql:
        container_name: "mysql"
        image: mysql:5.7.32
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - ./log:/logs/:rw
            - ./data:/var/lib/mysql/:rw
            - ./conf:/etc/mysql/conf.d/:rw
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: zhangshaohai
        restart: always
        networks:
            - mysql-net

networks:
    mysql-net:
        external: true
